# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyStride' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyStride
  
  #API
  pod 'AWSCore', '~> 2.6.0'
  pod 'AWSCognitoIdentityProvider', '~> 2.6.0'
  pod 'AWSAPIGateway', '~> 2.6.13'
  pod 'AWSLambda'
  
  #UI
  pod 'R.swift'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SVProgressHUD'
  pod 'ActionSheetPicker-3.0'
  
  
  target 'MyStrideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyStrideUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
